name: dict_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  go_router: ^8.0.5
  either_option: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: RBold
      fonts:
        - asset: assets/fonts/greyCliff-bold.ttf
    - family: RMedium
      fonts:
        - asset: assets/fonts/greyCliff-regular.ttf
    - family: RLight
      fonts:
        - asset: assets/fonts/greyCliff-regular.ttf
 